<a href="https://colab.research.google.com/github/POOJITHA1334/ML/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.array([1,3,4])
print(a)

[1 3 4]


In [ ]:
import numpy as np
a=np.array([1,3,4])
print(a.shape)

(3,)


In [ ]:
import numpy as np
a=np.ones((4,3,2))
print(a)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [ ]:
d=np.eye(5)
print(d)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


we can also use np.ones,np.zeros and np.random.random


In [ ]:
import numpy as np
d=np.arange(10,60,5)
print(d)

[10 15 20 25 30 35 40 45 50 55]


In [ ]:
f=np.linspace(0,20,6)
print(f)

[ 0.  4.  8. 12. 16. 20.]


data slicing in array:
slicing of an array with more than one dimension, you should specify the slice for each dimension.

In [ ]:
a=np.ones((2,2))
print(a)


[[1. 1.]
 [1. 1.]]


In [ ]:
a = np.array([[1, 2], [4, 5]])
b=a[1:2]
print(b)

[[4 5]]


In [ ]:
a=np.array([[2,3,4],[4,5,9]])
b=a[1:4,1:3]#first row 3 row and first column and and second column
print(b)

[[5 9]]


In [ ]:
a=np.array([[2,3,4,5],[4,5,9,6],[4,5,6,3]])
print(a)

[[2 3 4 5]
 [4 5 9 6]
 [4 5 6 3]]


In [ ]:
r1=a[1,:]#row 2 is displayed at a[1]
r2=a[1:2,:]# here shape differs so that the elments are shown in nested array
r3=a[[1],:]
print(r1,r1.shape)
print(r2,r2.shape)
print(r3,r3.shape)

[4 5 9 6] (4,)
[[4 5 9 6]] (1, 4)
[[4 5 9 6]] (1, 4)


In [ ]:
c1=a[:,1]
c2=a[:,1:2]
print(c1,c1.shape)
print(c2,c2.shape)

[3 5 5] (3,)
[[3]
 [5]
 [5]] (3, 1)


In [ ]:
import numpy as np
a=np.array([[1,2,3,4],[3,5,7,5],[6,8,9,0],[5,8,9,3]])
b=np.array([2,0,3,1])
print(a[np.arange(4)],b)

[[1 2 3 4]
 [3 5 7 5]
 [6 8 9 0]
 [5 8 9 3]] [2 0 3 1]


bool indexing

In [ ]:
a=np.array([[1,2],[3,4],[5,6]])
b=(a>2)
print(b)

[[False False]
 [ True  True]
 [ True  True]]


1 argmax(get index of maximum element in array
2 where(get index of elements that meet some condition

In [ ]:
a=np.array([1,5,6,-2,4,6,7,9])
print(np.argmax(a))
print(np.argmin(a))
print(np.argsort(a))
print(np.argsort(a)[::-1])
print(np.where(a<5)[0])
print(np.where(a>=a[np.argmax(a)])[0])


7
3
[3 0 4 1 2 5 6 7]
[7 6 5 2 1 4 0 3]
[0 3 4]
[7]


In [ ]:
a=[0]
a=np.append(a, [1,2,3,4])
print(a)

[0 1 2 3 4]


In [ ]:
a=np.array([[1,2,3,4],[3,5,7,5],[6,8,9,0],[5,8,9,3]])
a=np.sort(a,axis=0,kind='quicksort')
print(a)

[[1 2 3 0]
 [3 5 7 3]
 [5 8 9 4]
 [6 8 9 5]]


In [ ]:
import numpy as np
v=np.array([[1,2],[3,4]])
w=np.array([[4,6],[8,9]])
print(v.dot(w))

[[20 24]
 [44 54]]


In [ ]:
w=np.array([[1],[3],[9]])
z=w.squeeze()
print(z)
print(z.shape)

[1 3 9]
(3,)


In [ ]:
w=np.array([[1],[3],[9]])
y=w.reshape(-1,)
print(y)


[1 3 9]


rule 1:  

In [ ]:
a=np.array([1,2,3])
b=np.array([[0],[1],[2]])
c=a+b
a


array([1, 2, 3])

In [ ]:
a=np.array([1,2,3])
b=np.array([[0],[1],[3]])
c=a+b
c

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])